# Load config file and parameters
filename = 'input\comments.xlsx'
sheetname = 'Comments'

[columns]
sort = [
  "Heading 1",
  "Heading 2",
  "Heading 3",
]

# Numbered sort columns if sort-sort is set to 'worksheet'
numbered_sort = [
  "value1",
  "value2",
  "value3",
]

[columns.commentresponse]
# These are required to be specified.
comment = 'Comment Data'
response = 'Response'

[columns.other]
# The key "tag" is required. "tag" is appended to the end of each comment to
# provide a way of keeping track of comments and their commenter. Comment tags
# should be a unique text string not found anywhere else in the document if using
# these tags to create an index.
tag = 'Commenter Code'

[sort]
# Specify sorting of lowest-level (where comments and responses are).
# Comment Count (descending): 'count', Alphabetical (ascending): anything else
type = 'count'

# Where to get sort data from. 'worksheet' for columns specified under numbered sort,
# or 'config' for sort data from this configuration file.
sort = 'config'

# Specify custom sort of level 1. Use empty list [] for no custom sort.
# For headings not listed here, it will be at the end and sorted as specified above.
custom_level_1 = [
  "Group 5"
]
# This is a lump-all of all subheadings past Level 1. This really shines as a way to 
# bring something to the first position of all subheadings - like a "General" category
# or something. 
# If the lowest-level is sorted by comment count (sort-type, above), then this has no effect
# on lowest-level sorting characteristics (as they will be sorted by comment count).
custom_level_2 = [
]

[other]
# Specify whether what row header begins on. Assumes data starts immediately after.
header_row = 1
# Specify starting heading level (1 means begin at Heading 1)
outline_level = 2
# Specify whether to remove double spaces.
# Leading and trailing whitespace at the end of paragraphs are automatically trimmed.
# (true or false)
remove_double_spaces = true

[index]
# If any of these are set to true, Microsoft Word is 
mark_index_entries = true
# If mark_index_entries is false, this setting does nothing.
append_comment_index = true