# COMMENT-RESPONSE SCRIPT CONFIGURATION

automark = 'output/automark.docx'
filename = 'input/Alex_45 Day_Comments_Ref - Copy.xlsx'
header_row = 1
outline_level = 2
savename = 'output/section.docx'
sheetname = 'Comments Database'

[section.columns]
comment = 'CommentText'
comment_tag = 'Comment ID'
response = 'draft Agency Response'

[section.sort]
by_count = true
ordered = ["value1", "value2", "value3"]
title = [
  "FSOR section heading level 1",
  "FSOR section heading level 2",
  "FSOR section heading level 3",
]

[section.other.clean]
clean = true
trim = true

[section.other.custom]
comment_intro = 'Comment'
comment_intro_every_comment = false
intro_sep = ': '
response_intro = 'Response'

[section.other.quantity]
indicate_quantity = true
multiple_comments = "Multiple Comments: "
single_comment = "Comment: "
